### ISSUE TITLE
Allow to use node greater than v8

### ISSUE THREAD

**Issue by Fabianopb** [Fabianopb/express-react-ts-ci#7]
Currently the `package.json` is limiting the version of node to be `8.x`.
```json
"engines": {
  "node": "8.x",
  "yarn": "1.x"
}
```

We should allow developers to use *node > 8* and possibly run Travis on multiple versions.

**Comment by Alexius08** [comment]
If the only thing we have to do for this one is to allow running later versions of node, I'll tackle it.

**Comment by Fabianopb** [comment]
Hi @Alexius08, thanks for reaching out, but apparently this issue was solved in https://github.com/Fabianopb/express-react-ts-ci/pull/8. I hope you hadn't started it yet!
